gfroerli/firmware

platformio.ini
The current firmware probably won't run on it since we haven't tested
with it for a long time.
=> Remove LPC1786 support

Pipfile, Pipfile.lock
Platformio does not run on Python 3 yet.
Tracking issue: https://github.com/platformio/platformio-core/issues/895
=> Require Python 2.7 in Pipfile

Pipfile, Pipfile.lock
That way it should be possible to just execute `pipenv update` without
breaking anything.
=> Don't use star dependency in Pipfile

upload.jlink
The environment was renamed in caa470539a2f601f3d031ceb12e9f6eb430a63f3.
=> Fix JLink upload script

Cargo.toml
There was a breaking change in nighly:
https://users.rust-lang.org/t/psa-breaking-change-panic-fmt-language-item-removed-in-favor-of-panic-implementation/17875
=> Fix build by updating panic-semihosting

src/main.cpp
This PR contains code from #18, #23 and #24. Merge those first.
Replaces #12.
Right now, only the commit cf8eac0 is relevant.
This commit adds code to power down the MCU. Here's the power trace:
On the left you can see the MCU waking up and joining via OTAA. Then the measurements are sent and the LPC11U24 enters power down mode, which consumes 134 uA (highlighted area).
Then after 5s interval time, the MCU wakes up again and sends another packet (which arrives). During the next power down phase, current consumption is 2.17 mA. Due to reasons unknown to me, starting during the third power down phase, the current consumption is 4.58 mA.
But the main issue is that after the second sleep phase, the RN2483 does not wake up anymore, even though a break condition + 0x55 byte are sent.
Needs some …
=> Power down

src/main.cpp
We need to handle spreading factor / data rate in a better way. See #30.
For now, disable ADR and hardcode SF to 9.
=> Hardcode SF to 9

src/main.rs
Please note the difference between write and modify...
=> Fix bug where we disabled the IOCON bit when enabling GPIO

src/main.rs
This still results in the same configuration as using `Config::default()`, but it's now more explicit what's actually being used.
=> Explicit clock configuration

Cargo.lock, Cargo.toml
This includes our I2C and UART fixes!
=> Upgrade HAL to 0.6.0

Cargo.lock, Cargo.toml, src/main.rs
This allows running the code without gdb being attached.
For debug logging, we should probably use serial output, it's faster and we can keep the debug code in the firmware in case we need to debug a problem "in the field".
=> Remove semihosting

serial-debug.sh
Useful so we don't have to remember the debug serial config.
=> Add serial-debug.sh

Cargo.lock, Cargo.toml
The `tim6` branch got merged upstream :tada:
=> Fix build by changing stm32l0xx-hal dependency to existing branch

src/leds.rs, src/main.rs, src/version.rs
A simple hardware version detector on PA12 / PB4 / PB5.
Current output via serial:
Should we keep the hardware version as an integer, or should I map it to an enum (where 0 would correspond to `V2_0` and others would correspond to `Unknown(u8)`)?
=> Implement HardwareVersionDetector

.embed.toml, README.md
(Requires https://github.com/probe-rs/cargo-embed/pull/27. The old
config will still parse properly, but nothing happens when using the
`reset` config.)
=> .embed.toml: Add reset target

.circleci/config.yml, examples/delay.rs, src/delay.rs, src/lib.rs, src/main.rs
The HAL delay uses the systick timer (SYST). This timer is not available anymore when using RTIC with the scheduler.
Here's an implementation of DelayUs and DelayMs for TIM7 (with busy-looping until the update event of the timer is reached). It seems to work, although delays lower than ~4 µs cannot be achieved.
The precision seems to be good enough for one-wire to work:
Busy-looping was the easiest approach and works, but seems a bit wasteful. Is this busy-looping standard practice? Would it be better to schedule an interrupt and WFI during looping? (I'm not sure if this could be implemented cleanly in a standalone implementation because interrupt handling ist done by RTIC...)
I think in our case it should be fine because we only use the blocking delay for very short intervals during …
=> Add custom Tim7Delay

README.md, src/main.rs, src/monotonic_stm32l0.rs
Based on #77, merge that first.
Binary size increased by 1 KiB (33.88 -> 34.88) but the code is much more readable, especially once we add more scheduling!
=> Use RTIC scheduling system

.circleci/config.yml, Cargo.toml, src/lib.rs, src/main.rs, src/supply_monitor.rs
By compiling the binary and the panic-halt dependency only when
compiling for arm and only declaring no_std when not in test mode, we
allow for regular unit tests to be run on the host.
=> Add unit test support

Cargo.lock, Cargo.toml, src/lib.rs, src/main.rs, src/measurement.rs
=> Implement new measurement wire format

serial-debug.sh
In newer releases, the python-serial package does not build the
`miniterm.py` binary anymore.
Instead, access miniterm through `python3 -m serial.tools.miniterm`.
=> Call miniterm through Python

Cargo.lock, Cargo.toml, examples/delay.rs, memory.x, src/main.rs
On boot, when a panic message is found, print it to serial and carry on.
=> Switch from panic-halt to panic-persist

src/config.rs, src/lib.rs, src/main.rs
My proposal would be to put the configuration variables (e.g. interval, encryption keys, etc) in EEPROM. We have 2x3 KiB of EEPROM, that should be plenty.
See diff for my proposed memory layout. If you agree, I can implement this.
The EEPROM can be read simply by reading the corresponding raw memory addresses. To write the EEPROM, we can use a custom binary based on `probe-rs`, which reads a TOML file with the config and writes to the target's EEPROM. Alternatively, instead of writing to the target directly, we could generate a binary file or hexfile and flash that to the target using `cargo-embed`.
(Support for flashing EEPROM is WIP.)
=> EEPROM based config

firmware/src/monotonic_stm32l0.rs
After the timer value rolls over the newer more recent value will be
negative. Calculating the duration_since with an older still positive
Instant results in a panic due to subtracting with overflow:
panicked at 'attempt to subtract with overflow', src/monotonic_stm32l0.rs:149:20
Fixes #96 
See also https://github.com/rtic-rs/rtic-examples/commit/beabbe39d5c4bb37c8c453de704aeba0b8c118b0
=> monotonic impl: Fix panic due to timer rollover

firmware/src/main.rs, firmware/src/measurement.rs, firmware/src/supply_monitor.rs
Additionally, the data printing has been refactored and simplified using the `delimit!` macro.
Fixes #93.
Marked as draft because I could not test this yet. However, the PR can already be reviewed!
=> Send actual voltage as part of measurement

common/src/lib.rs
Got a bad reviewer last time :wink:
=> Fix typo in crate documentation

jlink.cfg, stm32l0.cfg
Just copied the file from /usr/share/openocd/scripts/target/stm32l0.cfg
and /usr/share/openocd/scripts/interface/jlink.cfg.
Then patched the jlink file again to use the SWD inferface.
With this update I can start openocd, but I'm still not able to properly debug with it.
=> Update openocd configuration files

firmware/src/main.rs
Previously the code panicked when re-scheduling a measurement:
panicked at 'assertion failed: dur.inner < (1 << 15)', src/monotonic_stm32l0.rs:167:9
The reason is that we're scheduling the next measurement 5000ms into the
future:
ctx.schedule
.start_measurements(ctx.scheduled + 5000.millis())
Unfortunately our 16bit timer cannot do this:
> Because the timer has 16 bits, it will overflow every 125 µs * 2^16 =
> ~8.19 seconds. Due to overflow checking, we can only safely use one
> half of the available timer range, meaning that we can safely schedule
> tasks 4.096 seconds into the future, with a resolution of 125 µs.
Thus, reduce the timeout to 4s. In the future, we'll use the RTC to
schedule the next measurement.
=> Fix panic in scheduler due to potential timer overflow

firmware/.embed.toml
When the microcontroller is in standby, it will not allow attaching.
Thus, we need to attach under reset in those cases.
=> Always flash under reset

firmware/Cargo.lock, firmware/Cargo.toml, firmware/examples/delay.rs, firmware/src/delay.rs, firmware/src/leds.rs, firmware/src/lib.rs, firmware/src/main.rs, firmware/src/rtc.rs, firmware/src/supply_monitor.rs
Changes:
The initialization value is `2001-01-01 00:00:00`. (We don't need a correct absolute datetime, we just need to measure elapsed time.) The RTC keeps its time as long as the power is not removed.
When starting, the RTC datetime and the uptime is printed to serial, followed by the config and base measurement plan:
The wakeup cycle is calculated by using `uptime_seconds // wakeup_interval_seconds`. For every measurement type, the appropriate `wakeup_cycle % nth_XXX == 0` calculation is done. If it's 0, the measurement is enabled in the base measurement plan. (The base measurement plan may be modified later based on availability of sensors.)
Refs #72.
=> RTC wakeup counter

firmware/src/main.rs
Makes it easier to spot in the log.
=> Prefix data transmission logs with emoji

firmware/Cargo.lock, firmware/Cargo.toml, firmware/examples/delay.rs, firmware/src/main.rs, firmware/src/monotonic_stm32l0.rs
This touched a lot of our code, so it may be hard to review. Except for the monotonic impl, it should be all mechanical changes without change in behavior. It works on my device 😉
- RTIC 1.0 docs: https://rtic.rs/dev/book/en/
- Migration guide: https://rtic.rs/dev/book/en/migration/migration_v5.html
Some relevant changes:
- The monotonic implementation had to be re-done completely.
- With the new trait, things become simpler, but we cannot use TIM6 anymore because it doesn't have a capture/compare register. Instead, I used LPTIM, which has the advantage that it could be used to schedule tasks while in a low power state, which means that we could further optimize by putting the microcontroller in one of those low-power states when waiting for a scheduled task (but when not yet in standby). …
=> Upgrade RTIC to 1.0.0

cli-utils/src/bin/config-flasher.rs
This allows flashing targets that are in sleep mode.
=> Config flasher: Attach under reset

firmware/Cargo.lock, firmware/Cargo.toml, firmware/examples/supply_monitor.rs
This is the base example which works with the current code. This can be merged until #128 with the actual supply monitor improvements is ready.
=> Add supply monitor example
